server:
  servlet:
    encoding:
      force: true
      force-response: true

spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    generate-unique-name: false
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
